name: Diagnóstico listado Charter
permissions: { contents: read }
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: debug-charter
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Cache de navegadores Playwright para acelerar
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-chromium-v1
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Instalar dependencias y Chromium
        run: |
          npm i --no-audit --no-fund
          npx playwright install chromium

      - name: Diagnóstico listado
        run: node scripts/step4.js

      - name: Subir artefactos debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.run_id }}
          path: docs/debug/**
          if-no-files-found: warn

      - name: Mostrar stats
        if: always()
        run: |
          test -f docs/debug/STATS.json && cat docs/debug/STATS.json || echo "Sin STATS"
```0
