name: Build dataset
permissions: { contents: write }
on:
  workflow_dispatch:
  schedule: [ { cron: "0 2 * * *" } ]  # 02:00 Europa/Madrid

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ms-playwright-${{ runner.os }}-v1
          restore-keys: |
            ms-playwright-
      - name: Instalar deps
        run: |
          npm i --no-audit --no-fund
          npx playwright install --with-deps
      - name: Construir dataset
        run: node scripts/sweep_charter.js
      - name: Snapshot diario
        run: |
          mkdir -p docs/history
          cp docs/charter.geojson docs/history/$(date +%F).geojson || true
      - name: Commit si hay cambios
        run: |
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add docs/charter.geojson docs/history/*.geojson 2>/dev/null || true
          git diff --cached --quiet && echo "Sin cambios" && exit 0
          git commit -m "data: update $(date +%F)"
          git push
