name: Build dataset
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # 02:00 Europe/Madrid
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Node version
        run: node -v
      - name: Build dataset
        run: node scripts/fetch_charter.js
      - name: Snapshot diario
        run: |
          mkdir -p docs/history
          cp docs/charter.geojson docs/history/$(date +%F).geojson || true
      - name: Commit si hay cambios
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/charter.geojson docs/history/*.geojson 2>/dev/null || true
          git diff --cached --quiet && echo "Sin cambios" && exit 0
          git commit -m "data: update $(date +%F)"
          git push
