name: Probe Charter get-map
permissions: { contents: write }
on: { workflow_dispatch: {} }

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Ejecutar sonda
        run: node scripts/step4.js
      - name: Commit debug
        run: |
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add docs/debug/probe.json 2>/dev/null || true
          git diff --cached --quiet && echo "Sin cambios" && exit 0
          git commit -m "probe: $(date +%F_%T)"
          git push
