name: Build dataset (ciudades)
permissions: { contents: write }
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Construir dataset
        run: node scripts/crawl_charter_from_city_pages.js
      - name: Commit si hay cambios
        run: |
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add docs/charter.geojson 2>/dev/null || true
          git diff --cached --quiet && echo "Sin cambios" && exit 0
          git commit -m "data: update $(date +%F)"
          git push
