name: Build dataset
permissions: { contents: write }
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: node scripts/sweep_charter.js
      - run: |
          mkdir -p docs/history
          cp docs/charter.geojson docs/history/$(date +%F).geojson || true
      - run: |
          git config user.name bot
          git config user.email bot@users.noreply.github.com
          git add docs/charter.geojson docs/history/*.geojson
          git diff --cached --quiet && echo "Sin cambios" && exit 0
          git commit -m "data: update $(date +%F)"
          git push
